nativescript-community/nativescript-vscode-extension

- adapter/pathTransformer.ts
- adapter/sourceMaps/sourceMapTransformer.ts
- adapter/sourceMaps/sourceMaps.ts
- webkit/utilities.ts
- webkit/webKitDebugAdapter.ts
> Support preliminary brakepoints

- src/services/NsCliService.ts
Fix debugger not attaching and hanging the android process when attempting to connect too early to device, before the application has started.
@ivanbuhov
> Fix #77 sync command not working on android devices 

- src/debug-adapter/webKitDebugAdapter.ts
- src/project/androidProject.ts
- src/project/iosProject.ts
- src/project/project.ts
- src/project/streamScanner.ts
Sync debug configuration reattaches the VSCode debugger on every file sync.
> Enable debugging with livesync

- src/custom-typings/debugProtocolExtensions.d.ts
- src/debug-adapter/webKitDebugAdapter.ts
Fixes: https://github.com/NativeScript/nativescript-vscode-extension/issues/57
> Enable loading more than 20 call frames

- package.json
- src/debug-adapter/connection/INSDebugConnection.ts
- src/debug-adapter/connection/androidConnection.ts
- src/debug-adapter/connection/iosConnection.ts
- src/debug-adapter/webKitDebugAdapter.ts
Fixes: https://github.com/NativeScript/nativescript-vscode-extension/issues/90
This implementation works properly only on iOS. 
On the Android side we are translating the hit count to the semantically equivalent [`ignoreCount`](https://github.com/NativeScript/nativescript-vscode-extension/compare/buhov/hit-count-support?expand=1#diff-2dc41c475bbe3598bb11d3ad87e235c9R461) property as described in the [V8 debugging protocol spec](https://github.com/v8/v8/wiki/Debugging-Protocol#request-setbreakpoint) but still after setting a breakpoint with a hit count set to some positive number, the value of `ignoreCount` is ignored and the breakpoint is hit every single time. ping @blagoev
> [iOS] Support for breakpoints with ignoreCount in iOS only

- src/debug-adapter/webKitDebugAdapter.ts
When the TNS process has been closed we're still hanging the debugger as if you can still do something. 
This is easily reproducible if there is need for interactive input from the user. For example if you have two provisioning profiles and run `launch ios` from the app it will try to find a provisioning profile for you, get confused, can't get a decision and return an error for you to pass the `teamId` as an arg. After that the TNS exits. Currently we hang, now we raise the terminate event.
Another way to test:
- Run IOS in Simulator
- Close the Simulator. The process should be terminated.
> When the TNS process is finished - terminate the debugger process, too.

- src/ipc/extensionServer.ts
When the User doesn't have any Provisioning Profiles the directory's files cannot be listed and therefore an ENOENT exceptions was thrown. This caused the promise to hang forever and the processes hangs. Now we catch all exceptions when trying to read all Provisioning Profile's teams and return empty teams array if something goes wrong.
> Handle all exceptions when searching for Teams and ignore them

- package.json
- src/debug-adapter/webKitDebugAdapter.ts
- src/ipc/extensionServer.ts
This PR does 2 things:
1. Pin the node modules to versions that actually work. The reason? I cloned the repo and built the package (worked) then installed the plugin in VSCode (worked), then launched on iOS (fail, without an error message *anywhere*). With help of `npm view <package name> versions time --json` I figured out what would have been the version of all (dev) dependencies in `package.json` at the time of the last release, and those worked just fine. So I decided to pin to those exact versions (and two of them with the `~` prefix as that doesn't do harm in those cases.
2. Save the selected iOS team id to a workspace setting. Closes #138. The team id is saved in the workspace settings which can be removed by the user if he wants to switch to a different team. But I'm not sure …
> Pin node modules & save the iOS Team ID

- .vscode/launch.json
- package.json
- src/debug-adapter/adapter/sourceMaps/sourceMapTransformer.ts
- src/debug-adapter/webKitDebugAdapter.ts
- src/project/androidProject.ts
- vscode seems to handle 'drive-letter' in both small letter and capital letter, this makes some conflict while dealing with breakpoints. Currently the _sourceMaps tree in sourceMapTransformer.ts has all paths with small letter but on the setBreakpoints method the debugger adapter receives a capital letter.
- Use tree-kill to kill the tns process because process kill throws an error "Unknown signal: SIGQUIT". Also on windows only the parent process is killed which in our case is the shell process which has started the "tns debug command". The actual node process remains.
- Increase time before "readyForConnection" event because in my tests it seems that 500 milliseconds are not enough.
- Remove some obsolete properties from launch.json and added a composite configuration for easier …
> Fixing typescript breakpoints on windows

- package.json
Use https zip instead of git for dependencies. There were some connection problems with ``npm install`` on several machines with git protocol.
> Use https zip instead of git for dependencies

- src/debug-adapter/webKitDebugAdapter.ts
- src/project/androidProject.ts
- src/project/iosProject.ts
- src/project/project.ts
Stop debugger on TypeScript compile error.
> Stop debugger on TypeScript compile error

- src/debug-adapter/nativeScriptDebug.ts
- src/debug-adapter/nativeScriptDebugAdapter.ts
- src/main.ts
- src/services/buildService.ts
- src/services/extensionHostServices.ts
- src/tests/nativeScriptDebugAdapter.tests.ts
Fixes LiveSync by restarting session. Each time we got terminate sessions event we wait 10 sec to get new port. If we get new port for debugging we restart the session.
Move cli process to main process because each restart the session is created(but the tns process is not killed) and we don't have reference to the long running tns process. Also conceptual it's better to have the cli output in the extension output but not in the debug console.
Fixes Debug Console messages and show exactly in which file is the console log.
> Fixes LiveSync

- CHANGELOG.md
- package.json
- src/debug-adapter/nativeScriptDebugAdapter.ts
- src/debug-adapter/nativeScriptPathTransformer.ts
- src/tests/nativeScriptDebugAdapter.tests.ts
- src/tests/nativeScriptPathTransformer.tests.ts
- src/tests/pathTransformData.ts
Debugging is not working when project has `nsconfig.json` and the path to `app` directory is changed. The problem is that on device the directory is always called `app`, but NativeScript projects can rename it locally to `src` for example.
In order to fix the issue, check if there's nsconfig.json file and replace the `app` from the device path with the local name of the app directory.
This fixes debugging for new Angular templates.
Fix for https://github.com/NativeScript/nativescript-vscode-extension/issues/205
> fix: debugging is not working when app path is changed

- package.json
The application templates were updated to have 'src/' folder instead
of 'app/'. The path overrides should be updated as well.
fixes https://github.com/NativeScript/nativescript-vscode-extension/issues/213
> fix: update the source map path overrides for webpack

- package.json
- src/debug-adapter/nativeScriptDebugAdapter.ts
Currently source map path for webpack is set to `src` which is not correct for js projects and in case when the user changes appDirPath property in `nsconfig` file.
Rel to: https://github.com/NativeScript/nativescript-vscode-extension/issues/222
> fix: set correct source map path for webpack

- src/debug-adapter/nativeScriptDebugAdapter.ts
Increase the timeout for reconnect after liveSync. Currently, if you have stopped on a breakpoint and apply a change in the code (for iOS), the session will not be able to restart for 10 seconds. So increase the timeout as a temp solution for the moment.
> fix: increase timeout for reconnecting

- package.json
- src/project/androidProject.ts
- src/project/iosProject.ts
- src/project/project.ts
- src/services/buildService.ts
Related to: https://github.com/NativeScript/nativescript-vscode-extension/issues/144
> feat: add Test configurations allowing unit tests debugging

- package.json
Currently build of the extension fails as the versions of dependencies and devDependencies are not hardcoded and we receive version of `@types/lodash` that is incompatible with the TypeScript we are using.
For `@types/lodash` we have the following dist-tags:
```
{ latest: '4.14.122',
'ts2.0': '4.14.50',
'ts2.1': '4.14.56',
'ts2.2': '4.14.112',
'ts2.3': '4.14.112',
'ts2.4': '4.14.112',
'ts2.5': '4.14.112',
'ts2.6': '4.14.121',
'ts2.7': '4.14.121',
'ts2.8': '4.14.122',
'ts2.9': '4.14.122',
'ts3.0': '4.14.122',
'ts3.1': '4.14.122',
'ts3.2': '4.14.122',
'ts3.3': '4.14.122',
'ts3.4': '4.14.122' }
```
In our case we are using TypeScript 2.6.2, so set the version of `@types/lodash` to 4.14.121.
Also set strict versions for all other dependencies (based on what has been installed in my local …
> fix: use strict versions for all dependencies

- package.json
- src/debug-adapter/nativeScriptDebugAdapter.ts
- src/debug-adapter/nativeScriptPathTransformer.ts
- src/debug-adapter/nativeScriptTargetDiscovery.ts
- src/tests/nativeScriptPathTransformer.tests.ts
Update chrome-debug-adapter package to latest version and apply required changes in the code according to the changes in the new version.
As the webRoot is no longer passed to `targetUrlToClientPath` method, set the webRoot when initializing the instance of `NativeScriptPathTransformer`
> chore: update chrome-debug-adapter to latest version

- package.json
- src/debug-adapter/nativeScriptDebug.ts
- src/debug-adapter/nativeScriptDebugAdapter.ts
- src/debug-adapter/nativeScriptPathTransformer.ts
- src/debug-adapter/nativeScriptSourceMapTransformer.ts
- src/main.ts
- src/tests/nativeScriptDebugAdapter.tests.ts
Add support for Debug + HMR - currently it is not working, as when a hot-module is applied, VSCode does not know that the current hot-module is mapped to the actual changed file (main-view-model) for example.
To fix this, add SourceMapTransformer and plug in the scriptParsed method. When breakpoint is set, cache it (in nativeScriptDebugAdapter), so once hot-module is applied, set the breakpoints from its original file (i.e. main-view-model) in the newly applied hot module.
This is exactly how Chrome works.
Also, add logic in pathTransformer to map files from `platforms` dir when debugging on iOS.
Related to: https://github.com/NativeScript/nativescript-vscode-extension/issues/221
> feat: add support for debug with hmr

- CHANGELOG.md
- package.json
- src/debug-adapter/nativeScriptDebugAdapter.ts
Currently when you set library in your webpack.config.js, you are able to debug your app on windows, but not on macOS and Linux. The problem is in the way `path.join` works for UNIX style paths. The current code appends `./` in the beginning of the path, which is normally a full path:
```
path.join(`.//Users/vladimirov/Work/nativescript-cli-2/scratch/app1`, "test1.js")
'Users/vladimirov/Work/nativescript-cli-2/scratch/app1/test1.js'
```
As you can see, this removes the starting `/` from the full path, so the VSCode extension is unabel to get correct path to the searched file (webpack.config.js in our case).
On windows the result is:
```
> path.join("./D:\\Work\\nativescript-cli\\scratch\\app1", "test1.js")
'D:\\Work\\nativescript-cli\\scratch\\app1\\test1.js'
```
> fix: debugging apps with library set should work on all platforms

- package.json
- src/debug-adapter/nativeScriptDebugAdapter.ts
- src/main.ts
- src/tests/nativeScriptDebugAdapter.tests.ts
I believe this addresses #278 and [#8930](https://github.com/NativeScript/NativeScript/issues/8930). I have never been able to properly debug an Angular based NativeScript project in vscode using this "nativescript-vscode-extension" because vscode always says `"Breakpoint ignored because generated code not found (source map problem?)"`.  Regular plain JavaScript projects work as expected but not with Angular.  After combing through the debug console and logging output from the extension, I found the problem to be that the path of the source files have `app/app` in it when it should be `src/app`.  For example, with a fresh NativeScript Angular HelloWorld project `ns create ns-angular-project --ng` the vscode debugger says the path is: …
> Bug fix vscode debugger when using Angular based NativeScript projects.

- .vscode/tasks.json
- README.md
- package-lock.json
- package.json
- src/analytics/analyticsService.ts
- src/analytics/guaService.ts
- src/debug-adapter/nativeScriptDebugAdapter.ts
- src/debug-adapter/nativeScriptTargetDiscovery.ts
- src/services/buildService.ts
- src/services/iOSTeamService.ts
- src/tests/nativeScriptDebugAdapter.tests.ts
On iOS it never worked because by not specifying the address the address 127.0.0.1 was used and the websocket server rejected the connection.
In Android it is just the opposite, it rejects the localhost connection and accepts 127.0.0.1 so it has been handled to establish the address that will then be used by the `NativeScriptTargetDiscovery` class.
Also added logic to add sourceMapPathOverrides for files `["js", "ts", "vue", "svelte", "jsx", "tsx"]` since they didn't seem to work and breakpoints didn't work they worked. Now this property[ `devtoolNamespace`](https://github.com/orgs/NativeScript/discussions/9693#discussioncomment-1774475)  is not necessary since the name of the package.json.name is searched and added to sourceMapPathOverrides, but it has also been added the logic so that …
> fix iOS connection to loopback address (127.0.0.1) and sourceMapPathOverrides for all file extensions
